[build]
  command = "node index.js"
  publish = "dist"
  base = "./"
  ignore = '! git describe --tags --exact-match HEAD'
  # ignore = 'if git describe --tags --exact-match HEAD; then true; else echo ; fi'




